# SPDX-FileCopyrightText: 2021 moderncv maintainers <github.com/moderncv>
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  reuse-compliance-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v5
